### ISSUE TITLE
Linking failed on Debian based linux.

### ISSUE THREAD

**Issue by nanfang2000** [ardera/flutter-pi#117]
The linker failed to find the reference functions in the libraries.
I fixed it by putting the LDFLAG to after the Objects.
	$(CC) $(REAL_CFLAGS) $(OBJECTS) **_$(REAL_LDFLAGS)_** -o out/flutter-pi

A doc just explained this issue:
https://stackoverflow.com/a/43305704/388520

**Comment by ardera** [comment]
Okay, thanks, I'll fix that in the Makefile.
