### ISSUE TITLE
SunFounder RasPad Touch not work

### ISSUE THREAD

**Issue by akilinomendez** [ardera/flutter-pi#12]
The raspberry open de app and apparently all work but Touchscreen dont capture  click in any /dev/input/event.

Any idea.

Thank you.

**Comment by ardera** [comment]
I hope I understood your question correctly. You mean that flutter-pi won't register taps from your SunFounder RaspPad and you tried all /dev/input/event files?

Could you please run `sudo evtest` (install evtest using `sudo apt install evtest`), select your the input device that corresponds to your touchscreen (the friendly names of the input devices are printed out), tap a few times on the RaspPad while evtest is running, and send me the complete output of evtest?

**Comment by akilinomendez** [comment]
Thanks for your answer,

It really only records touches on some sites of the application. I have played with width and ratio because the pixels are 1280 x 800 and 10.10 '.

It seems like only one zone is clickable while the application occupies the entire screen.

**Comment by ardera** [comment]
> I have played with width and ratio because the pixels are 1280 x 800 and 10.10 '.

What _exactly_ did you change? I assume by width you mean the physical width (and height) of the display, and by ratio the device pixel ratio used by the flutter engine, which is stored in the `width_mm`, `height_mm` and `pixel_ratio` variables in `flutter-pi.c`?
(You actually don't need to manually calculate pixel_ratio, it's calculated automatically using width_mm and height_mm, or if these are not given, using the physical size data supplied by the screen)

> It seems like only one zone is clickable while the application occupies the entire screen.

And what is this zone? Is it, for example, a rectangle, or a quarter of the screen?


Again, an evtest log (including the part where you select the input device) would really help me figure out what's going on. Maybe you could do some taps that are in the zone that flutter-pi recognizes, and some in the zone where it doesn't, and then send me log.

**Comment by akilinomendez** [comment]
I reset  to default flutter-pi.

OK, i created one app  in flutter to get position on tap, only work in left-top small square in screen with this result:


flutter: tapped!
flutter: tap down 90.0, 748.0
flutter: tap up 90.0, 748.0
flutter: tapped!
flutter: tap down 38.0, 763.0
flutter: tap down 12.0, 752.0
flutter: tap down 30.0, 687.0
flutter: tap down 68.0, 645.0
flutter: tap down 68.0, 603.0
flutter: tap down 176.0, 607.0
flutter: tap down 202.0, 526.0
flutter: tap down 90.0, 702.0
flutter: tap down 86.0, 771.0
flutter: tap down 81.0, 672.0
flutter: tap down 107.0, 790.0
flutter: tap down 211.0, 775.0


And evtest tap in similary zone:

Event: time 1573817756.307149, type 3 (EV_ABS), code 57 (ABS_MT_TRACKING_ID), value 688
Event: time 1573817756.307149, type 3 (EV_ABS), code 53 (ABS_MT_POSITION_X), value 715
Event: time 1573817756.307149, type 3 (EV_ABS), code 54 (ABS_MT_POSITION_Y), value 1218
Event: time 1573817756.307149, type 1 (EV_KEY), code 330 (BTN_TOUCH), value 1
Event: time 1573817756.307149, type 3 (EV_ABS), code 0 (ABS_X), value 715
Event: time 1573817756.307149, type 3 (EV_ABS), code 1 (ABS_Y), value 1218
Event: time 1573817756.307149, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 0
Event: time 1573817756.307149, -------------- SYN_REPORT ------------
Event: time 1573817756.314118, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 8000
Event: time 1573817756.314118, -------------- SYN_REPORT ------------
Event: time 1573817756.320117, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 16000
Event: time 1573817756.320117, -------------- SYN_REPORT ------------
Event: time 1573817756.326115, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 24000
Event: time 1573817756.326115, -------------- SYN_REPORT ------------
Event: time 1573817756.333117, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 32000
Event: time 1573817756.333117, -------------- SYN_REPORT ------------
Event: time 1573817756.339114, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 40000
Event: time 1573817756.339114, -------------- SYN_REPORT ------------
Event: time 1573817756.345117, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 48000
Event: time 1573817756.345117, -------------- SYN_REPORT ------------
Event: time 1573817756.353119, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 56000
Event: time 1573817756.353119, -------------- SYN_REPORT ------------
Event: time 1573817756.358118, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 64000
Event: time 1573817756.358118, -------------- SYN_REPORT ------------
Event: time 1573817756.364121, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 72000
Event: time 1573817756.364121, -------------- SYN_REPORT ------------
Event: time 1573817756.372121, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 80000
Event: time 1573817756.372121, -------------- SYN_REPORT ------------
Event: time 1573817756.378120, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 88000
Event: time 1573817756.378120, -------------- SYN_REPORT ------------
Event: time 1573817756.383121, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 96000
Event: time 1573817756.383121, -------------- SYN_REPORT ------------
Event: time 1573817756.391119, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 104000
Event: time 1573817756.391119, -------------- SYN_REPORT ------------
Event: time 1573817756.397123, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 112000
Event: time 1573817756.397123, -------------- SYN_REPORT ------------
Event: time 1573817756.402125, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 120000
Event: time 1573817756.402125, -------------- SYN_REPORT ------------
Event: time 1573817756.410125, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 128000
Event: time 1573817756.410125, -------------- SYN_REPORT ------------
Event: time 1573817756.416125, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 136000
Event: time 1573817756.416125, -------------- SYN_REPORT ------------
Event: time 1573817756.422132, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 144000
Event: time 1573817756.422132, -------------- SYN_REPORT ------------
Event: time 1573817756.429128, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 152000
Event: time 1573817756.429128, -------------- SYN_REPORT ------------
Event: time 1573817756.435130, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 160000
Event: time 1573817756.435130, -------------- SYN_REPORT ------------
Event: time 1573817756.441126, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 168000
Event: time 1573817756.441126, -------------- SYN_REPORT ------------
Event: time 1573817756.449129, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 176000
Event: time 1573817756.449129, -------------- SYN_REPORT ------------
Event: time 1573817756.454131, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 184000
Event: time 1573817756.454131, -------------- SYN_REPORT ------------
Event: time 1573817756.460133, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 192000
Event: time 1573817756.460133, -------------- SYN_REPORT ------------
Event: time 1573817756.468130, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 200000
Event: time 1573817756.468130, -------------- SYN_REPORT ------------
Event: time 1573817756.473133, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 208000
Event: time 1573817756.473133, -------------- SYN_REPORT ------------
Event: time 1573817756.479132, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 216000
Event: time 1573817756.479132, -------------- SYN_REPORT ------------
Event: time 1573817756.487137, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 224000
Event: time 1573817756.487137, -------------- SYN_REPORT ------------
Event: time 1573817756.493135, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 232000
Event: time 1573817756.493135, -------------- SYN_REPORT ------------
Event: time 1573817756.498134, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 240000
Event: time 1573817756.498134, -------------- SYN_REPORT ------------
Event: time 1573817756.506137, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 248000
Event: time 1573817756.506137, -------------- SYN_REPORT ------------
Event: time 1573817756.512138, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 256000
Event: time 1573817756.512138, -------------- SYN_REPORT ------------
Event: time 1573817756.517138, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 264000
Event: time 1573817756.517138, -------------- SYN_REPORT ------------
Event: time 1573817756.525138, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 272000
Event: time 1573817756.525138, -------------- SYN_REPORT ------------
Event: time 1573817756.531140, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 280000
Event: time 1573817756.531140, -------------- SYN_REPORT ------------
Event: time 1573817756.537140, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 288000
Event: time 1573817756.537140, -------------- SYN_REPORT ------------
Event: time 1573817756.544141, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 296000
Event: time 1573817756.544141, -------------- SYN_REPORT ------------
Event: time 1573817756.550145, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 304000
Event: time 1573817756.550145, -------------- SYN_REPORT ------------
Event: time 1573817756.556143, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 312000
Event: time 1573817756.556143, -------------- SYN_REPORT ------------
Event: time 1573817756.564145, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 320000
Event: time 1573817756.564145, -------------- SYN_REPORT ------------
Event: time 1573817756.569143, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 328000
Event: time 1573817756.569143, -------------- SYN_REPORT ------------
Event: time 1573817756.575143, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 336000
Event: time 1573817756.575143, -------------- SYN_REPORT ------------
Event: time 1573817756.583149, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 344000
Event: time 1573817756.583149, -------------- SYN_REPORT ------------
Event: time 1573817756.588146, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 352000
Event: time 1573817756.588146, -------------- SYN_REPORT ------------
Event: time 1573817756.594147, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 360000
Event: time 1573817756.594147, -------------- SYN_REPORT ------------
Event: time 1573817756.602150, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 368000
Event: time 1573817756.602150, -------------- SYN_REPORT ------------
Event: time 1573817756.608146, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 376000
Event: time 1573817756.608146, -------------- SYN_REPORT ------------
Event: time 1573817756.613151, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 384000
Event: time 1573817756.613151, -------------- SYN_REPORT ------------
Event: time 1573817756.621153, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 392000
Event: time 1573817756.621153, -------------- SYN_REPORT ------------
Event: time 1573817756.627152, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 400000
Event: time 1573817756.627152, -------------- SYN_REPORT ------------
Event: time 1573817756.633155, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 408000
Event: time 1573817756.633155, -------------- SYN_REPORT ------------
Event: time 1573817756.640153, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 416000
Event: time 1573817756.640153, -------------- SYN_REPORT ------------
Event: time 1573817756.646156, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 424000
Event: time 1573817756.646156, -------------- SYN_REPORT ------------
Event: time 1573817756.652156, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 432000
Event: time 1573817756.652156, -------------- SYN_REPORT ------------
Event: time 1573817756.659153, type 3 (EV_ABS), code 57 (ABS_MT_TRACKING_ID), value -1
Event: time 1573817756.659153, type 1 (EV_KEY), code 330 (BTN_TOUCH), value 0
Event: time 1573817756.659153, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 440000
Event: time 1573817756.659153, -------------- SYN_REPORT ------------


evtest  tap in opposite:

Event: time 1573817720.686856, type 3 (EV_ABS), code 57 (ABS_MT_TRACKING_ID), value 687
Event: time 1573817720.686856, type 3 (EV_ABS), code 53 (ABS_MT_POSITION_X), value 16241
Event: time 1573817720.686856, type 3 (EV_ABS), code 54 (ABS_MT_POSITION_Y), value 9535
Event: time 1573817720.686856, type 1 (EV_KEY), code 330 (BTN_TOUCH), value 1
Event: time 1573817720.686856, type 3 (EV_ABS), code 0 (ABS_X), value 16241
Event: time 1573817720.686856, type 3 (EV_ABS), code 1 (ABS_Y), value 9535
Event: time 1573817720.686856, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 0
Event: time 1573817720.686856, -------------- SYN_REPORT ------------
Event: time 1573817720.692790, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 8000
Event: time 1573817720.692790, -------------- SYN_REPORT ------------
Event: time 1573817720.697787, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 16000
Event: time 1573817720.697787, -------------- SYN_REPORT ------------
Event: time 1573817720.705786, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 24000
Event: time 1573817720.705786, -------------- SYN_REPORT ------------
Event: time 1573817720.711790, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 32000
Event: time 1573817720.711790, -------------- SYN_REPORT ------------
Event: time 1573817720.716788, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 40000
Event: time 1573817720.716788, -------------- SYN_REPORT ------------
Event: time 1573817720.724789, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 48000
Event: time 1573817720.724789, -------------- SYN_REPORT ------------
Event: time 1573817720.730826, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 56000
Event: time 1573817720.730826, -------------- SYN_REPORT ------------
Event: time 1573817720.736789, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 64000
Event: time 1573817720.736789, -------------- SYN_REPORT ------------
Event: time 1573817720.743792, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 72000
Event: time 1573817720.743792, -------------- SYN_REPORT ------------
Event: time 1573817720.749791, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 80000
Event: time 1573817720.749791, -------------- SYN_REPORT ------------
Event: time 1573817720.755793, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 88000
Event: time 1573817720.755793, -------------- SYN_REPORT ------------
Event: time 1573817720.762794, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 96000
Event: time 1573817720.762794, -------------- SYN_REPORT ------------
Event: time 1573817720.768794, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 104000
Event: time 1573817720.768794, -------------- SYN_REPORT ------------
Event: time 1573817720.774829, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 112000
Event: time 1573817720.774829, -------------- SYN_REPORT ------------
Event: time 1573817720.782797, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 120000
Event: time 1573817720.782797, -------------- SYN_REPORT ------------
Event: time 1573817720.787796, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 128000
Event: time 1573817720.787796, -------------- SYN_REPORT ------------
Event: time 1573817720.793838, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 136000
Event: time 1573817720.793838, -------------- SYN_REPORT ------------
Event: time 1573817720.801803, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 144000
Event: time 1573817720.801803, -------------- SYN_REPORT ------------
Event: time 1573817720.807797, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 152000
Event: time 1573817720.807797, -------------- SYN_REPORT ------------
Event: time 1573817720.812798, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 160000
Event: time 1573817720.812798, -------------- SYN_REPORT ------------
Event: time 1573817720.820798, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 168000
Event: time 1573817720.820798, -------------- SYN_REPORT ------------
Event: time 1573817720.826798, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 176000
Event: time 1573817720.826798, -------------- SYN_REPORT ------------
Event: time 1573817720.831800, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 184000
Event: time 1573817720.831800, -------------- SYN_REPORT ------------
Event: time 1573817720.839804, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 192000
Event: time 1573817720.839804, -------------- SYN_REPORT ------------
Event: time 1573817720.845802, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 200000
Event: time 1573817720.845802, -------------- SYN_REPORT ------------
Event: time 1573817720.851804, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 208000
Event: time 1573817720.851804, -------------- SYN_REPORT ------------
Event: time 1573817720.858802, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 216000
Event: time 1573817720.858802, -------------- SYN_REPORT ------------
Event: time 1573817720.864806, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 224000
Event: time 1573817720.864806, -------------- SYN_REPORT ------------
Event: time 1573817720.870811, type 3 (EV_ABS), code 53 (ABS_MT_POSITION_X), value 16207
Event: time 1573817720.870811, type 3 (EV_ABS), code 54 (ABS_MT_POSITION_Y), value 9599
Event: time 1573817720.870811, type 3 (EV_ABS), code 0 (ABS_X), value 16207
Event: time 1573817720.870811, type 3 (EV_ABS), code 1 (ABS_Y), value 9599
Event: time 1573817720.870811, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 232000
Event: time 1573817720.870811, -------------- SYN_REPORT ------------
Event: time 1573817720.875802, type 3 (EV_ABS), code 57 (ABS_MT_TRACKING_ID), value -1
Event: time 1573817720.875802, type 1 (EV_KEY), code 330 (BTN_TOUCH), value 0
Event: time 1573817720.875802, type 4 (EV_MSC), code 5 (MSC_TIMESTAMP), value 240000
Event: time 1573817720.875802, -------------- SYN_REPORT ------------

**Comment by ardera** [comment]
Ah, I know what's going on. The X and Y values reported by your touchscreen are not aligned to the pixel grid, they're between 0 and 16384 (as it seems) instead of between 0 and 1280 (for example).

That's perfectly legal by the spec, just didn't think it'd be a problem in practice. Should be an easy fix, I just need to query min and max X and Y values using some ioctl's.

**Comment by ardera** [comment]
#15 
Could you please test if it works with the newest version?
if it does, I will close this issue.

**Comment by akilinomendez** [comment]
thanks, as soon as I can try it

**Comment by akilinomendez** [comment]
It works perfectly thanks, I will continue trying a greeting.
