### ISSUE TITLE
Support for the Raspberry Pi 2

### ISSUE THREAD

**Issue by bela333** [ardera/flutter-pi#141]
I tried the project on my Raspberry Pi 2 because I didn't notice the "This means flutter-pi won't work on a Pi Zero, Pi 1, or Pi 2." part of the README and it seemed to work just fine. Because the Pi 2 has a ARMv7 processor, I assume this notice was put here because of problems that might happen with hardware 3D acceleration.
Is it possible that it uses software rendering?
Is there a way to verify support?

**Comment by ardera** [comment]
> Because the Pi 2 has a ARMv7 processor

Oh you're right, I thought it had an ARMv6 one. I'll update this. There should be no problems with hardware acceleration. It's just that the dart SDK needs ARMv7 at least.
