### ISSUE TITLE
Implement vsync 

### ISSUE THREAD

**Issue by suyulin** [ardera/flutter-pi#156]
hi,
pi 3B and pi400 has tearing, Could you optimize it ?

**Comment by ardera** [comment]
vsync is implemented, every tearing that remains is due to the driver / firmware. If you're not using the official 7 inch panel you can try switching to the full-KMS driver, see [my reply](https://github.com/ardera/flutter-pi/issues/94#issuecomment-703747693) on issue 94 for more info.
