### ISSUE TITLE
  compile arm64 app.so

### ISSUE THREAD

**Issue by suyulin** [ardera/flutter-pi#157]
hi,
arm app.so compile is ok.
but   compile arm64 app.so is error.
`Setting VM flags failed: Unrecognized flags: sim_use_hardfp, use-integer-division`

**Comment by ardera** [comment]
You can try using `--sim-use-hardfp` instead of `--sim_use_hardfp` and leaving away the `--no-use-integer-division` flag when invoking `gen_snapshot`

**Comment by tmathews** [comment]
For anyone wondering it seems you don't need this flag any longer.
