### ISSUE TITLE
trouble running app in debug mode

### ISSUE THREAD

**Issue by mortenboye** [ardera/flutter-pi#160]
I'm setting up a new RPi CM4 to run Flutter-Pi and have gone through the motions listed in the readme. 
However, when running the app on device I get this error in the console:

```
[flutter-pi] The flutter engine was built for release (AOT) mode,
             but flutter-pi was not started up in release mode. 
             Either you swap out the libflutter_engine.so 
             with one that was built for debug mode, or you start
             flutter-pi with the --release flag and make sure
             a valid "app.so" is located inside the asset bundle
             directory.
```

Question is: how do I swap out libflutter_engine?

**Comment by ardera** [comment]
Oops, my bad. Somehow must've copied the profile engine over the debug engine while I updated my build scripts.
Fixed it now
