### ISSUE TITLE
FLUTTER UPDATE

### ISSUE THREAD

**Issue by kekko7072** [ardera/flutter-pi#173]
After I update the dart SDK I have this issue, is there a way to fix or is linked to something else?
```
`[ERROR:engine/src/flutter/shell/common/shell.cc(242)] Dart Error: Can't load Kernel binary: Invalid SDK hash.
[ERROR:engine/src/flutter/runtime/dart_isolate.cc(169)] Could not prepare isolate.
[ERROR:engine/src/flutter/runtime/runtime_controller.cc(401)] Could not create root isolate.
[ERROR:engine/src/flutter/shell/common/shell.cc(571)] Could not launch engine with configuration.
flutter: Observatory listening on http://127.0.0.1:41021/1QtkyJcllj4=/`
```

After the update I am running Flutter 2.0.5
```
Doctor summary (to see all details, run flutter doctor
-v):
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.2.3
    20D91 darwin-x64, locale it-IT)
[✓] Android toolchain - develop for Android devices
    (Android SDK version 31.0.0-rc2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.55.2)
[✓] Connected device (2 available)
```

EDIT: After I downgraded using `flutter downgrade 2.0.4` it works so I will wait the engine update.

**Comment by ardera** [comment]
thanks! updated them

**Comment by kekko7072** [comment]
Ok thank you so I just  `git pull && git checkout origin/master` to make It run right?

**Comment by ardera** [comment]
yep exactly

**Comment by kekko7072** [comment]
@ardera 
Hey new DART UPDATE available, can you update the engine?

At the end I wasn't able to update using `git pull && git checkout origin/master` I deleted and reinstalled the flutter-pi. 
Where should I run this code? In the RPi or in the Linux VM ?  If in the RPi in witch directory?

Thank you so much I am developing crazy things using Flutter RPI you changed my life!

**Comment by ardera** [comment]
> @ardera 
> Hey new DART UPDATE available, can you update the engine?
> 
> At the end I wasn't able to update using `git pull && git checkout origin/master` I deleted and reinstalled the flutter-pi. 
> Where should I run this code? In the RPi or in the Linux VM ?  If in the RPi in witch directory?

updated them (was already working on it when you wrote)

You execute them in your cloned engine binaries repo. I'm sorry but I won't go more into detail, a tutorial on git may help you further.

> Thank you so much I am developing crazy things using Flutter RPI you changed my life!

thx, appreciate it
