### ISSUE TITLE
kDebugMode not being set

### ISSUE THREAD

**Issue by Charlie9830** [ardera/flutter-pi#193]
Hi Ardera.

I am using flutter-pi as part of a Yocto build.
Based off of [jwinarkse's](https://github.com/jwinarske/meta-flutter) build.

The engine is built in release mode, as is my Flutter App. However, the Dart constant `kDebugMode` is evaluating to true at runtime.

The Flutter documentation suggests the follow about the `kDebugMode` constant.

> More specifically, this is a constant that is true if the application was not compiled with '-Ddart.vm.product=true' and 
> '-Ddart.vm.profile=true'. 

[Source](https://api.flutter.dev/flutter/foundation/kDebugMode-constant.html)

I am not skilled with C or C++, would I be correct in assuming that those flags need to be set whilst compiling the embedder?

**Comment by ardera** [comment]
no, those flags are set when generating the AOT snapshot using the `gen_snapshot` executable. See [the `building the app.so` section in the readme](https://github.com/ardera/flutter-pi#building-the-appso-for-running-your-app-in-releaseprofile-mode), step 4. The commandline argument `-Ddart.vm.product=true` is what sets that flag.
