### ISSUE TITLE
Engine update for Flutter 2.5.0

### ISSUE THREAD

**Issue by goncalo-almeida-mc** [ardera/flutter-pi#198]
Flutter 2.5.0 stable is out

**Comment by leddy231** [comment]
I just built my project with flutter 2.5 and pushed the app to my pi without any issue, what would need to be updated?

**Comment by ardera** [comment]
thanks for the reminder, working on it!

**Comment by ardera** [comment]
- resolved in https://github.com/ardera/flutter-engine-binaries-for-arm/commit/6266897c4e08ed2da966b9ea01a5c102a05b392e
