### ISSUE TITLE
Touch Screen Models with the best performance 

### ISSUE THREAD

**Issue by bvic23** [ardera/flutter-pi#200]
Dear ardera,

First of all, I love your project! I have been developing Flutter apps for ~3 years but I'm pretty new to Raspberry.

Could you please advise me on the touch screen models I can achieve that 50-60 FPS (and 50 Hz touch processing)?

I'm aware submitting a GH issue might not be appropriate way to get this info I just don't know other way to reach out.

Keep up the good work, I hope I can contribute to it sometimes later.

Thanks

**Comment by ardera** [comment]
> First of all, I love your project! I have been developing Flutter apps for ~3 years but I'm pretty new to Raspberry.

Thanks, I appreciate it!


> Could you please advise me on the touch screen models I can achieve that 50-60 FPS (and 50 Hz touch processing)?

That's a good question, I just use the raspberry pi one myself. Could be just any 3rd party screen is better. You could ask on the flutter discord what touchscreens people are using there

> I'm aware submitting a GH issue might not be appropriate way to get this info I just don't know other way to reach out.

Nah it's fine, though a ping on the flutter discord (link at the top of the readme, #custom-embedders channel) would've worked too I guess

> Keep up the good work, I hope I can contribute to it sometimes later.

sure, could always use some help!
