### ISSUE TITLE
Missing extension Byte exception

### ISSUE THREAD

**Issue by Sona-098** [ardera/flutter-pi#209]
Hi ,

I am using latest flutter engine 2.5.3 with flutter version also 2.5.3

When I try to run the built in app that is counter app in Raspberry 3 model b+, I am getting - Unhandled exception: format exception: Unexpected extension Byte.

I did not change anything in the code which is as it is(Built in counter app). And also I have seen the same error when I tried with Gallery app.

Could you please help me with it. 

Below is the log.

detected VideoCore IV as underlying graphics chip, and VC4 as the driver.
Reporting modified GL_EXTENSIONS string that doesn't contain non-working extensions.
flutter: Observatory listening on http://127.0.0.1:41343/EblMPzbt7iU=/
[compositor] Could not move cursor to front. Mouse cursor may be invisible. drmdev_plane_get_max_zpos_value: Invalid argument
[compositor] GPU does not supported the desired HW plane order.
             Some UI layers may be invisible.
[ERROR:engine/src/flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: FormatException: Missing extension byte (at offset 9)
#0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1787:7)
#1      Utf8Decoder.convert (dart:convert/utf.dart:322:42)
#2      StringCodec.decodeMessage (package:flutter/src/services/message_codecs.dart:44:25)
#3      JSONMessageCodec.decodeMessage (package:flutter/src/services/message_codecs.dart:99:44)
#4      JSONMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:147:54)
#5      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
<asynchronous suspension>
#6      SystemChrome.setApplicationSwitcherDescription (package:flutter/src/services/system_chrome.dart:254:5)
<asynchronous suspension>

Any help would be appreciated.

**Comment by ardera** [comment]
Hey, sorry just noticed I forgot to reply.
This probably some bug inside the platform channel encoder / decoder in flutter-pi.

I fixed some stuff related to that recently, maybe that fixed this problem too?
