### ISSUE TITLE
Compatibility issues

### ISSUE THREAD

**Issue by limbouser** [ardera/flutter-pi#21]
Will this only work on a Raspbian version without GUI and will mouse pointer be visible if I'm using mouse pointer as an input device? If an OS with GUI will also work, can you provide me it's image download link or version details?

**Comment by ardera** [comment]
> Will this only work on a Raspbian version without GUI

`flutter-pi` only works when no desktop environment is running, so for example you could use raspbian-lite (or as you said, a raspbian version without GUI). An OS with GUI will _not_ work.

> and will mouse pointer be visible if I'm using mouse pointer as an input device?

`flutter-pi` is not yet able to render the mouse pointer, so you won't see a mouse pointer when using a mouse as an input device. It's on my todo-list though.

Note that `flutter-pi` is not really meant for desktop usage. You can use flutter-pi for example:
- if you're developing a car computer and want to use flutter for the UI
- for interactive digital signage
- for some kind of home control unit
- etc . . .

If you're currently using an OS with GUI and just want to run some generic flutter apps, you can still easily run flutter apps (i think). Google provides official support for that. [See here.](https://github.com/flutter/flutter/wiki/Desktop-shells)

**Comment by limbouser** [comment]
Thanks.
