### ISSUE TITLE
SPI  touchscreen not working [ADS7846]

### ISSUE THREAD

**Issue by Marouen-Hammami** [ardera/flutter-pi#212]
Hi, 
I'm having trouble using the touchscreen on RPi 4. I started the app using `flutter-pi -i "/dev/input/event5" -d "154,86" /test.app` .The app starts fine and works well with the mouse, but the touchscreen make any action. 
This is what i get on the terminal when i start the app through ssh.

###### <asynchronous suspension>
_______________________________________________________
And here's the evtest log when i tap on the screen :

###### Event: time 1640882425.693607, -------------- SYN_REPORT ------------
__________________________________________
 
Am I doing something wrong ? I already checked the exisiting issues and none of them actually helped.

**Comment by ardera** [comment]
Hey,
to be sure, have you tried running without the `-i <...>` option? 

Can you try running `libinput debug-events`, touch the screen a few times and send me the complete output?

**Comment by Marouen-Hammami** [comment]
Thank you for the quick answer.

> to be sure, have you tried running without the `-i <...>` option?
Yes i did and nothing changed.
> Can you try running `libinput debug-events`, touch the screen a few times and send me the complete output?

-event0   DEVICE_ADDED     Telink Wireless Receiver Mouse    seat0 default group1  cap:p left scroll-nat scroll-button
-event1   DEVICE_ADDED     Telink Wireless Receiver Consumer Control seat0 default group1  cap:kp scroll-nat
-event2   DEVICE_ADDED     Telink Wireless Receiver System Control seat0 default group1  cap:k
-event3   DEVICE_ADDED     Telink Wireless Receiver          seat0 default group1  cap:k
-event4   DEVICE_ADDED     ADS7846 Touchscreen               seat0 default group2  cap:t ntouches 1 calib
 event4   TOUCH_DOWN       +0.000s      -1 (0) 42.50/27.59 (1741.00/1130.00mm)
 event4   TOUCH_FRAME      +0.000s
 event4   TOUCH_MOTION     +0.020s      -1 (0) 42.58/27.44 (1744.00/1124.00mm)
 event4   TOUCH_FRAME      +0.020s
 event4   TOUCH_MOTION     +0.040s      -1 (0) 42.55/27.56 (1743.00/1129.00mm)
 event4   TOUCH_FRAME      +0.040s
 event4   TOUCH_MOTION     +0.060s      -1 (0) 42.58/27.59 (1744.00/1130.00mm)
 event4   TOUCH_FRAME      +0.060s
 event4   TOUCH_MOTION     +0.080s      -1 (0) 42.41/27.49 (1737.00/1126.00mm)
 event4   TOUCH_FRAME      +0.080s
 event4   TOUCH_UP         +0.097s
 event4   TOUCH_FRAME      +0.097s
 event4   TOUCH_DOWN       +2.100s      -1 (0) 41.87/75.02 (1715.00/3073.00mm)
 event4   TOUCH_FRAME      +2.100s
 event4   TOUCH_MOTION     +2.120s      -1 (0) 41.92/75.24 (1717.00/3082.00mm)
 event4   TOUCH_FRAME      +2.120s
 event4   TOUCH_MOTION     +2.140s      -1 (0) 41.89/75.05 (1716.00/3074.00mm)
 event4   TOUCH_FRAME      +2.140s
 event4   TOUCH_MOTION     +2.160s      -1 (0) 41.87/75.00 (1715.00/3072.00mm)
 event4   TOUCH_FRAME      +2.160s
 event4   TOUCH_MOTION     +2.180s      -1 (0) 41.89/75.05 (1716.00/3074.00mm)
 event4   TOUCH_FRAME      +2.180s
 event4   TOUCH_MOTION     +2.200s      -1 (0) 41.94/75.12 (1718.00/3077.00mm)
 event4   TOUCH_FRAME      +2.200s
 event4   TOUCH_MOTION     +2.220s      -1 (0) 41.85/75.15 (1714.00/3078.00mm)
 event4   TOUCH_FRAME      +2.220s
 event4   TOUCH_UP         +2.237s
 event4   TOUCH_FRAME      +2.237s
 event4   TOUCH_DOWN       +3.920s      -1 (0) 47.02/27.56 (1926.00/1129.00mm)
 event4   TOUCH_FRAME      +3.920s
 event4   TOUCH_MOTION     +3.940s      -1 (0) 47.90/27.34 (1962.00/1120.00mm)
 event4   TOUCH_FRAME      +3.940s
 event4   TOUCH_MOTION     +3.960s      -1 (0) 48.00/27.29 (1966.00/1118.00mm)
 event4   TOUCH_FRAME      +3.960s
 event4   TOUCH_MOTION     +3.980s      -1 (0) 48.00/27.27 (1966.00/1117.00mm)
 event4   TOUCH_FRAME      +3.980s
 event4   TOUCH_MOTION     +4.000s      -1 (0) 47.85/27.54 (1960.00/1128.00mm)
 event4   TOUCH_FRAME      +4.000s
 event4   TOUCH_UP         +4.037s
 event4   TOUCH_FRAME      +4.037s
 event4   TOUCH_DOWN       +4.680s      -1 (0) 45.53/76.42 (1865.00/3130.00mm)
 event4   TOUCH_FRAME      +4.680s
 event4   TOUCH_MOTION     +4.700s      -1 (0) 45.53/76.32 (1865.00/3126.00mm)
 event4   TOUCH_FRAME      +4.700s
 event4   TOUCH_MOTION     +4.720s      -1 (0) 45.46/76.29 (1862.00/3125.00mm)
 event4   TOUCH_FRAME      +4.720s
 event4   TOUCH_MOTION     +4.740s      -1 (0) 45.56/76.29 (1866.00/3125.00mm)
 event4   TOUCH_FRAME      +4.740s
 event4   TOUCH_MOTION     +4.760s      -1 (0) 45.51/76.25 (1864.00/3123.00mm)
 event4   TOUCH_FRAME      +4.760s
 event4   TOUCH_UP         +4.777s
 event4   TOUCH_FRAME      +4.777s

**Comment by ardera** [comment]
Mh okay nothing unusual there. It probably has something to do with the fact that it's single touch, I've never tried running with that, but not sure what's the problem exactly.

I'll add some logging to `user_input.c`

**Comment by Marouen-Hammami** [comment]
So , I added some logging to `user_input.c` in function `process_libinput_events()`.
When randomly taping on the screen in different positions, I got a response. After further digging i noticed that the screen responds but the x and y axis are swapped.

**Comment by Marouen-Hammami** [comment]
UPDATE:
I swapped X and Y and inverted the Y axis. I also had to manually set `display_width` and `display_height` in line 833 and 834 of `user_input.c`. I think I have to do the same thing on `on_touch_motion()` to get more reliable results.

**Comment by ardera** [comment]
If the touchscreen doesn't report correct coordinates, you should calibrate it, see [here](https://github.com/ardera/flutter-pi/issues/164#issuecomment-841879291). What changes did you have to make to `display_width` and `display_height` though?

**Comment by Marouen-Hammami** [comment]
> If the touchscreen doesn't report correct coordinates, you should calibrate it, see [here](https://github.com/ardera/flutter-pi/issues/164#issuecomment-841879291). 
I tried the calibration process that you mentioned. The X and Y are now in the right place but : 
- X range is actually Y range.
- Y axis is inverted. the 0 is on top and max at bottom 
- Y range is X range.

The transforamtion matrix doesn't actually invert axes, it either translate or / and rotate them.

>What changes did you have to make to `display_width` and `display_height` though?

They had 0 as a value which is a bit odd. So i replaced them with 1024 and 600. 
here's how i made it work :
`y = 599 - libinput_event_touch_get_x_transformed(touch_event, 600-1);`
`x = libinput_event_touch_get_y_transmformed(touch_event,1024-1);`
I know this is not the most elegant way to do it , but it might help cover more use cases.

**Comment by ardera** [comment]
> The transforamtion matrix doesn't actually invert axes, it either translate or / and rotate them.

Sorry but that's wrong. Those are pretty basic use cases and that's the reason why libinput uses a 3x3 matrix, even though we only have 2-dimensional coordinates. It's also the reason computer games use 4x4 matrices for 3-dimensional coordinates.

Even if you're screen had some weird setup, with the transformation matrix you can basically represent any equation system of the following form: *(Note that x, y, x' and y' are normalized device coordinates, so they are in the range 0..1)*
```
x' = a*x + b*y + c*1
y' = d*x + e*y + f*1
```

For example, if you want `y'` to be the inverted `x` range, you set `d = -1`, `e = 0` and `f = 1`. That'll make the bottom equation `y' = 1 - x`. 

> Y axis is inverted. the 0 is on top and max at bottom

Not sure that's a problem, the origin (0, 0) should be at the top left, so if 0 is on top and max is at the bottom that's all fine I think.

The props you'd need to specify are:
1. If you want to swap X and Y and also invert Y:
    ```
    ATTRS{name}=="device name", ENV{LIBINPUT_CALIBRATION_MATRIX}="0.0 1.0 0.0 -1.0 0.0 1.0"
    ```
2. If you just want to swap X and Y, you need to set:
    ```
    ATTRS{name}=="device name", ENV{LIBINPUT_CALIBRATION_MATRIX}="0.0 1.0 0.0 1.0 0.0 0.0"
    ```

> They had 0 as a value which is a bit odd. So i replaced them with 1024 and 600.

`display_width` and `display_height` are 0 at first (when `user_input_new` is called) because user input is initialized before the display is initialized. They only get filled with real values inside [`flutterpi_fill_view_properties`](https://github.com/ardera/flutter-pi/blob/821a5c6a222e5ac05471ee7610b64e745e63bc4d/src/flutter-pi.c#L1185). Did you maybe read them out before `flutterpi_fill_view_properties` is called?

**Comment by Marouen-Hammami** [comment]
oh ,i get it now.
It seems to work fine with the right transformation matrix.
Thank you for the help .

**Comment by ardera** [comment]
@Marouen-Hammami np, glad it works now 👍
