### ISSUE TITLE
Hardware alternatives to raspberry pi?

### ISSUE THREAD

**Issue by qaler** [ardera/flutter-pi#249]
Raspberry pi has been much more expensive than previous years, I wonder if there are alternative hardwares that are also able to run flutter?

**Comment by ardera** [comment]
The cheapest I could find that could work is the [Banana Pi M2 Zero](https://www.pollin.de/p/banana-pi-m2-zero-810854?utm_source=geizhals.de&utm_medium=pvgl&campaign=pvgl/geizhals.de&channelid=psm&campaign=PVGL/geizhals.de), though I don't know what the price is for you, maybe some other board is cheaper.

the things you need to look for are:
- at least 512MB RAM (1GB if you want to be on the safe side)
- any CPU will work, but for example the Pi 3 A+ has 4 1.40GHz Cortex A53 cores and runs at 50-60fps (so a single A7 at 0.7GHz isn't gonna cut it)
- you need a GPU. I don't know how fast the Mali-400 MP2 of the Banana Pi is, could be it's not enough to run at good enough FPS

Though it also depends on the resolution of your display. The lower the display resolution, the higher the FPS of course. I'm also working on an update where you can specify the pixel format, so you can use `RGB565` as pixel format for example. That'll maybe introduce some color banding, but will increase FPS too.
