### ISSUE TITLE
[flutter-pi] Could not find a connected connector!

### ISSUE THREAD

**Issue by FlorianAlt** [ardera/flutter-pi#266]
I have a special use case which requires that flutter-pi starts without a connected display (or the display is connected but the power is switched off by a hardware switch in the power-line).

Unfortunately I was not able to get this working with the known settings in `/boot/config.txt` like `hdmi_force_hotplug`, `hdmi_group`, `hdmi_mode`.
The Pi is recognizing the force_hotplug but flutter-pi still tells me `[flutter-pi] Could not find a connected connector!` when I try to start it.

I have also tried to start flutter-pi with a connected and powered display and then switch it off.
This works for days but after about 10-14 days flutter-pi crashes.
Due to this special use case I was not able to receive log files from the user but this behavior was reproducible - not the timeframe but the behavior happened multiple times. 
As long as the monitor is still powered but in standby everything is fine - when the power is switched off flutter-pi crashes after days.

**Comment by ardera** [comment]
`hdmi_force_hotplug` is only recognized by the fake-KMS driver AFAIK, so check if you have that one enabled

Would it be possible to enable / disable the display backlight in your case instead of switching it on/off?

**Comment by FlorianAlt** [comment]
gnargh... i am feeling like an idiot -.-
Thanks for the KMS/FKMS hint! This did the trick...
I tried all the HDMI Settings with `dtoverlay=vc4-kms-v3d` which was not working.

With the following settings everything is working as expected.
When rebooting the pi without a connected TV my flutter-pi service is starting up.
As soon as I am connecting the TV on HDMI0 (or powering it up) it shows the application with 1080p resolution.

My /boot/config.txt:
```
# uncomment if hdmi display is not detected and composite is being output
hdmi_force_hotplug=1

# uncomment to force a specific HDMI mode (this will force VGA)
hdmi_group=1
hdmi_mode=76
hdmi_force_mode=1

# Enable DRM VC4 V3D driver
dtoverlay=vc4-fkms-v3d
max_framebuffers=2
```

The HDMI settings / value-tables can be found here:
https://www.raspberrypi.com/documentation/computers/config_txt.html
