### ISSUE TITLE
Suport for mali GPU Tv Box Amlogic S905X

### ISSUE THREAD

**Issue by emboxs** [ardera/flutter-pi#268]
Is there a possibility for flutter-pi to support mali gpu, like the one on android tv box. I have tried it with armbian os but always get error

```
[modesetting] Could not commit atomic request. drmModeAtomicCommit: Permission denied
[compositor] Could not present frame. drmModeAtomicCommit: Permission denied
```

**Comment by ardera** [comment]
Does it work if you run flutter-pi with `sudo`? (Wouldn't recommend doing that in a production environment though)
If it doesn't work is something else using the display maybe?

**Comment by emboxs** [comment]
after running it with sudo I get an error like this:

`[flutter-pi] Warning: Could not load libflutter_engine.so from the asset bundle. dlopen: /home/station01/minipom/libflutter_engine.so: cannot open shared object file: No such file or directory. Trying to open libflutter_engine.so.debug...
flutter: The Dart VM service is listening on http://127.0.0.1:44151/K-DsTSFykPo=/
[compositor] GPU does not support reflecting the screen in Y-direction.
  This is required for rendering into hardware overlay planes though.
  Any UI that is drawn in overlay planes will look upside down.
[compositor] GPU does not supported the desired HW plane order.
  Some UI layers may be invisible.
[modesetting] Could not commit atomic request. drmModeAtomicCommit: Invalid argument
[compositor] Could not present frame. drmModeAtomicCommit: Invalid argument
[modesetting] Could not commit atomic request. drmModeAtomicCommit: Invalid argument
[compositor] Could not present frame. drmModeAtomicCommit: Invalid argument
`
any suggestions, what should i do?

**Comment by ardera** [comment]
Can you try running kmscube and see if it works?
