### ISSUE TITLE
Bundle Folder Structure

### ISSUE THREAD

**Issue by jwinarske** [ardera/flutter-pi#278]
@ardera Head's up on this.  I use bundle folder structure for ivi-homescreen/flutter-auto and meta-flutter.  It follows the linux GTK layout - post build.  Maybe via `--b` option, or whatever.  The optional components are very useful for debugging scenarios.

```
<bundle folder>
- data
    flutter_assets
    icuctl.dat <optional>
- lib
    libapp.so
    libflutter_engine.so <optional>
```

Patch here:  https://github.com/meta-flutter/meta-flutter/pull/160/files

The only concern is that the patch as-is would be a breaking change for your users that don't use meta-flutter.

**Comment by ardera** [comment]
Sure, would a build-flag work for that as well? Could also add a build-flag for the dunfell filesystem layout (that's mostly just `app.so` being called `libapp.so`, if #279 is resolved)

**Comment by jwinarske** [comment]
@ardera Yeah whatever best fits your plans.  A build flag is easy to manage.

**Comment by ardera** [comment]
- resolved in https://github.com/ardera/flutter-pi/pull/290
