### ISSUE TITLE
Unable to build Release/Profile mode

### ISSUE THREAD

**Issue by HauTranCong** [ardera/flutter-pi#287]
Hello Ardera
I read all this issues https://github.com/ardera/flutter-pi/issues/82 but i got the same error that **Invalid Kernel binary format version**, have you commit the updated engine-binaries yet. Thank you in advanced!

![image](https://user-images.githubusercontent.com/68090646/189517845-785d8bdf-4e1a-47d9-ba36-8324e46bff88.png)

**Comment by ardera** [comment]
They're updated for 3.3.2 now
