### ISSUE TITLE
Why we cannot build on target machine. E.g Raspberry pi?

### ISSUE THREAD

**Issue by KlausJokisuo** [ardera/flutter-pi#289]
Heya, first of all, thanks for your hard work. Keep it up!

In the readme, you mention multiple times that we cannot do all of the work on raspberry pi, but instead, use a development machine. :) 

Thanks.

**Comment by ardera** [comment]
You can try if it works now, back when I wrote most of the readme the flutter SDK didn't work on arm (neither 32- nor 64-bit)

**Comment by ardera** [comment]
Closing this now since it seems to be resolved.
