### ISSUE TITLE
Mouse support flutter-pi

### ISSUE THREAD

**Issue by marco-1988** [ardera/flutter-pi#293]
Hi

I tried to implement the sw side slider as suggested in this link:

https://gist.github.com/ardera/e7ddf7c8e477d258a26dfa9c40002626

But the cursor appears but doesn't move and I don't know if it clicks or not.

Any suggestion? The mouse works installing gdm in console, but when I open flutter-pi do not work, and the problem is not only that do not see the cursor, but doesn't click and do not move.

Thanks

**Comment by ardera** [comment]
Do you get touch events in flutter at all? Can you maybe add print calls inside https://gist.github.com/ardera/e7ddf7c8e477d258a26dfa9c40002626#file-mouse_cursor-dart-L47-L66 and see if they print anything? `onPointerDown` should be triggered when the mouse is clicked.

If they don't print anything, can you run the following commands on your pi and send me the complete output?
```shell
$ sudo apt install -y libinput-tools
$ libinput list-devices
$ libinput debug-events
```

Thanks!
