### ISSUE TITLE
Incorrect touchscreen coordinates

### ISSUE THREAD

**Issue by MyisCARRY** [ardera/flutter-pi#302]
Hello!
I have problem with my touchscreen - it works but I need to tap in the "opposite" corner of the screen to tap a button. I have also noticed that the X and Y axis are swapped - when I move with touch to the right the taps go down.
Weird thing is that it works perfectly fine when I am in desktop mode.

Raspberry Pi 4 B 4gb
4inch rpi lcd a with xpt2046 touch controller

Let me know what details/logs do you need

**Comment by ardera** [comment]
Hey, can you run this on your raspberry pi? It should help you calibrate the screen.
https://github.com/ardera/flutter_libinput_calibrator

**Comment by MyisCARRY** [comment]
I build bundle with the same flutter sdk version as engine binaries. Run the app on raspberry pi. Followed the instructions on screen and it worked :D

Thanks for help!

**Comment by ardera** [comment]
np, glad it helped :)
