### ISSUE TITLE
printer

### ISSUE THREAD

**Issue by AndroidDesigner** [ardera/flutter-pi#313]
Hi everyone.
I want to use a usb label printer with raspberry pi.
I did try different packages and plugins such as [printing](https://pub.dev/packages/printing) but none of them work with flutter-pi.
Do I have to use Linux commands such as ``lp`` directly or did you have use a flutter package/plugin successfully?

**Comment by ardera** [comment]
There's no printing package for flutter-pi I know of, I'm afraid. Technically you could port the printing package to flutter-pi, but that requires some low-level knowledge of flutter-pi and flutter plugins.
I'd try the `lp` approach you mentioned

**Comment by AndroidDesigner** [comment]
Do you think can we use ``lp`` command in flutter-pi?
There are multiple packages to run linux command in flutter (such as [process_run](https://pub.dev/packages/process_run))
Can you please test it in a sample project?

**Comment by ardera** [comment]
You don't need a package to run processes in dart, there's standard Dart API for that. (dart:io Process.run)

I think you should try it yourself, I'm pretty busy. :-)

**Comment by AndroidDesigner** [comment]
Unfortunately, I could not find a label printer with arm64 driver. so nothing is printed with ``lp`` and ``lpr`` and ``cups admin page``.
What is your solution?

**Comment by AndroidDesigner** [comment]
Finally I did it.
