### ISSUE TITLE
Error with the latest Raspbian Lite

### ISSUE THREAD

**Issue by limbouser** [ardera/flutter-pi#32]
Package dri was not found in the pkg-config search path.
Perhaps you should add the directory containing `dri.pc'
to the PKG_CONFIG_PATH environment variable
No package 'dri' found
Package dri was not found in the pkg-config search path.
Perhaps you should add the directory containing `dri.pc'
to the PKG_CONFIG_PATH environment variable
No package 'dri' found
cc -c -I./include  -DBUILD_ELM327_PLUGIN -DBUILD_TEST_PLUGIN -ggdb   -lrt -lflutter_engine -lpthread -ldl  src/flutter-pi.c -o out/obj/flutter-pi.o
In file included from src/flutter-pi.c:24:
/usr/include/xf86drm.h:40:10: fatal error: drm.h: No such file or directory
 #include <drm.h>
          ^~~~~~~
compilation terminated.
make: *** [Makefile:15: out/obj/flutter-pi.o] Error 1

The above error was found when I did the whole in a newly flashed Raspbian Lite image

**Comment by ardera** [comment]
should be fixed now. Don't know why `dri` was in the in the first place.
