### ISSUE TITLE
symbol lookup error: flutter-pi: undefined symbol: eglDestroyImage

### ISSUE THREAD

**Issue by felix2049** [ardera/flutter-pi#327]
I got an error message when I was running on [RK3588](https://www.rock-chips.com/a/en/index.html). How to solve it? 

flutter-pi /home/myhome/Documents/flutter_gallery .
flutter-pi: symbol lookup error: flutter-pi: undefined symbol: eglDestroyImage

**Comment by ardera** [comment]
Can you try the `feature/compositor-ng` branch?

**Comment by felix2049** [comment]
> 

Many thanks!
It Works!  !

Firstly I try compile with "gstreamer video player" related packages, failed with compile error. 
Then use apt remove them all, compile successed. 
Does it will be fixed and merged to master soon?

**Comment by ardera** [comment]
Not sure how soon, but i will be merged to master yes.

What's the compile error when compiling with the gstreamer video player packages?
