### ISSUE TITLE
Can i customize the resolution?

### ISSUE THREAD

**Issue by Mitsuha** [ardera/flutter-pi#332]
The resolution of my monitor is 2560\*1600, but it is recognized as 1920\*1080

I saw the issue #51 and found that the width and height cannot be hard code
can you add support for custom resolutions ?

Great project, thank you for your effort

```
[flutter-pi] WARNING: display didn't provide valid physical dimensions. The device-pixel ratio will default to 1.0, which may not be the fitting device-pixel ratio for your display.
==============Locale==============
Flutter locale:
  default: en_GB
  locales: en_GB en.UTF-8 en.UTF-8 en.UTF-8 en_GB en en.UTF-8
===================================
===================================
display mode:
  resolution: 1920 x 1080
  refresh rate: 60Hz
  physical size: 0mm x 0mm
  flutter device pixel ratio: 1.000000
===================================
```

**Comment by Mitsuha** [comment]
I tried `feature/compositor-ng` branch and i got other problems:

1\. Specifying the `--videomod`  parameter  will fail, the actucal output is still 1920\*1080, the error message is:  
```
root@user:~# flutter-pi --videomode 2560x1600@60 raspberry/
/home/user/flutter-pi/src/window.c: Didn't find a videomode matching "2560x1600"! Falling back to display preferred mode.
flutter: The Dart VM service is listening on http://127.0.0.1:33385/cv-2qQH3Fwg=/
```

2\. `flutter-pi` shows on the console that the output resolution is 1920\*1080, but the monitor prompts that it received 1920\*560  (This issue occurs on both branches. `master` and `feature/compositor-ng`)

I tried to specify the resolution in the configuration file of the Raspberry Pi, but it failed. Now I just want `flutter-pi` to output 1920\*1080 normally

**Comment by ardera** [comment]
are you sure your monitor supports that resolution? If it does, could be the EDID is broken

Can you do `sudo apt install libdrm-tests` and send me the complete output of `modetest -c`?
