### ISSUE TITLE
wrong touch position in Debian 10 Buster (aarch64)

### ISSUE THREAD

**Issue by AndroidDesigner** [ardera/flutter-pi#333]
Hello
I have a debian 10 buster touch panel and used the ``compositor-ng`` branch to be able to run my app ([issue_328](https://github.com/ardera/flutter-pi/issues/328)).
But I don't know why touch positions are wrong when I run the app (in both portrait & landscape).
for example, suppose I have a button in bottom-left of the screen. So if I click on it, nothing happens while if I click on bottom-right side of the screen, the button's event triggers.

I used ``sudo libinput debug-events`` to be able to check touched positions and it seems the (x,y) are correct (for example top-left shows 0/ 0 (0/ 0mm) and right-bottom shows 100/ 100 (1280/ 800mm)).
Also, ``$xrandr`` output:
```
xrandr
Screen 0: minimum 320 x 200, current 1280 x 800, maximum 8192 x 8192
DSI-1 connected primary 1280x800+0+0 right (normal left inverted right x axis y axis) 0mm x 0mm
   800x1280      56.24*+
```
what is the problem?
Are you sure touch handler in the ``compositor-ng`` branch is correct?

**Comment by ardera** [comment]
Nice that you got it working!

flutter-pi uses `libinput`, but other than that it's correct :) I also have [flutter_libinput_calibrator](https://github.com/ardera/flutter_libinput_calibrator) for this, but specifying an exact rotation matrix like you did is better

**Comment by AndroidDesigner** [comment]
The [flutter_libinput_calibrator](https://github.com/ardera/flutter_libinput_calibrator) is so useful too.
Thank you.
