### ISSUE TITLE
Attempted to move cursor while cursor is disabled.

### ISSUE THREAD

**Issue by AndroidDesigner** [ardera/flutter-pi#334]
Hi
I'm using the ``compositor-ng`` branch in a debian 10 buster aarch64.
I want to work with mouse but I will get the "Attempted to move cursor while cursor is disabled" error.
I checked the branch and saw the below code in the [source code](https://github.com/ardera/flutter-pi/blob/feature/compositor-ng/src/window.c)
```
if (has_pos) {
        if (window->cursor_enabled) {
            // move cursor
            ASSERT_NOT_NULL(window->move_cursor_locked);
            ok = window->move_cursor_locked(window, pos);
        } else {
            // !enabled && !window->cursor_enabled
            // move cursor while cursor is disabled
            LOG_ERROR("Attempted to move cursor while cursor is disabled.\n");
            ok = EINVAL;
        }
    }
```
How can I use the mouse cursor?

**Comment by ardera** [comment]
Can you try again with latest `feature/compositor-ng`? I've incorporated some fixes for mouse cursor support there
