### ISSUE TITLE
Mouse not working

### ISSUE THREAD

**Issue by GitHobi** [ardera/flutter-pi#337]
Hi there. I'm not sure if I'm missing something - or if it simply does not work, so I kindly ask for advice.
I have successfully installed flutter-pi and my test applications are running - but I have no mouse support.

In the output I see the following message:

```
...
[compositor] GPU does not supported the desired HW plane order.
[compositor] Preferred framebuffer depth for hardware cursor is not supported by flutter-pi.
[compositor] Could not set the mouse cursor buffer. drmModeSetCursor: Invalid argument
[flutter-pi] Error enabling / disabling mouse cursor. compositor_apply_cursor_state: Invalid argument
```

Are there any settings I have missed? (I'm on RPI3). 

Besides that: Impressive work! Thanks for that!

**Comment by ardera** [comment]
Can you try with the [feature/compositor-ng](https://github.com/ardera/flutter-pi/tree/feature/compositor-ng) branch?

**Comment by GitHobi** [comment]
Thanks for your response. 
Just gave it a try. With compositor-ng a mouse cursor is shown once I move the mouse. But the mouse cursor itself does not move, it sticks on the upper left corner :(
In the console I get a lot of such messages:
`compositor_ng.c: Attempted to move cursor while cursor is disabled.`

**Comment by ardera** [comment]
Can you try again with latest `feature/compositor-ng`? Added some fixes for mouse cursor support there :)

> Besides that: Impressive work! Thanks for that!

Thanks btw, appreciate it!

**Comment by GitHobi** [comment]
Just tried your latest version from feature/compositor-ng ... the mouse is not working as expected! Your fixes seem solve my issue!
Great job any many thanks!

**Comment by ardera** [comment]
Glad it's fixed :) I'll close this when `feature/compositor-ng` is merged into master.

**Comment by klushund** [comment]
Info: My Mouse problem (no mouse shown) is also solved in `feature/compositor-ng`
