### ISSUE TITLE
flutterpi_gstreamer_video_player error

### ISSUE THREAD

**Issue by AndroidDesigner** [ardera/flutter-pi#346]
Hi.
I have used the ``Single-frame stepping`` example of the [flutterpi_gstreamer_video_player](https://pub.dev/packages/flutterpi_gstreamer_video_player) package, but it results in the following error when call ``_controller.stepForward()``:
```
flutter-pi.c: Error handling platform message. plugin_registry_on_platform_message: Invalid argument
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(illegalargument, Expected `arg` to be a valid texture id., {receivedTextureId: -1, registeredTextureIds: []}, null)
```

Note:
I'm using latest version of the ``compositor-ng`` branch.

**Comment by ardera** [comment]
I just tried, it works fine for me. Can you please post the whole log?
