### ISSUE TITLE
Plugin Registry Initialization Error

### ISSUE THREAD

**Issue by limbouser** [ardera/flutter-pi#36]
While running flutter-pi in an embedded-linux build, it gets stuck at 

 `
Clearing current context...
finished display setup!
Initializing Application...
Initializing Plugin Registry...
Initialized Services plugin.
Could not initialize plugin registry: Illegal seek
`

Why would this be happening?

**Comment by ardera** [comment]
I have no idea.

You could try removing `-DBUILD_ELM327_PLUGIN` and `-DBUILD_TEST_PLUGIN` from the `Makefile` to see whether that makes a difference.

**Comment by ardera** [comment]
Oh my bad, forgot to return a zero in `Services_init`
