### ISSUE TITLE
video_player on raspberry pi 4 64 bit

### ISSUE THREAD

**Issue by beniskopf** [ardera/flutter-pi#382]
Hi, i'm trying to play video files on a raspberry pi 4 (64 bit). As stated in the docs i should use 
`$ sudo apt install libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-bad1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-ugly gstreamer1.0-plugins-bad gstreamer1.0-libav gstreamer1.0-alsa` + [https://pub.dev/packages/video_player](url). however it gives me this error message. any ideas how to fix this? maybe related to [https://github.com/ardera/flutter-pi/issues/360](url)

> [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: UnimplementedError: init() has not been implemented.
#0      VideoPlayerPlatform.init (package:video_player_platform_interface/video_player_platform_interface.dart:43)
#1      _videoPlayerPlatform (package:video_player/video_player.dart:28)
#2      VideoPlayerController.initialize (package:video_player/video_player.dart:430)
#3      _BumbleBeeRemoteVideoState.initState (package:miata_screen/filepicker.dart:117)
#4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5602)
#5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#7      Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#8      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
#9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#10     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#12     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#13     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#14     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#16     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#17     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
#18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#19     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#20     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
#21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#22     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#24     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#25     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#26     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#27     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
#28     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#30     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#31     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
#32     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#33     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#34     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#35     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#36     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#37     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#38     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
#39     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#41     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#42     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
#43     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#44     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#45     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#46     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#47     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#48     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#49     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
#50     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#51     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#52     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#53     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#54     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#55     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#56     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#57     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
#58     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#59     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#60     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#61     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
#62     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#63     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#64     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#65     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#66     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#67     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#68     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
#69     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#70     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#71     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#72     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
#73     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#74     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#75     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#76     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#77     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#78     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#79     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
#80     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#81     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#82     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#83     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#84     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#85     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#86     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#87     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
#88     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#89     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#90     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#91     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#92     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#93     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#94     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#95     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#96     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#97     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#98     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#99     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#100    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#101    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
#102    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#103    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#104    Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#105    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
#106    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#107    Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#108    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#109    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#110    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#111    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#112    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#113    Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#114    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
#115    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#116    Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#117    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#118    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#119    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#120    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#121    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
#122    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#123    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#124    Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#125    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#126    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#127    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#128    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#129    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#130    Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#131    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#132    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#133    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#134    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#135    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#136    Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#137    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#138    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#139    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#140    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#141    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
#142    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#143    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#144    Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#145    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#146    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#147    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#148    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#149    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#150    Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#151    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#152    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#153    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#154    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#155    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#156    Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#157    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
#158    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#159    Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#160    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#161    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#162    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#163    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#164    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#165    Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#166    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#167    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#168    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#169    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#170    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#171    Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#172    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#173    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#174    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#175    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#176    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
#177    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#178    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#179    Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#180    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#181    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#182    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#183    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#184    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
#185    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#186    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#187    Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#188    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#189    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#190    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#191    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#192    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
#193    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#194    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#195    Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#196    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
#197    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#198    Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#199    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#200    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#201    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#202    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#203    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#204    Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#205    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#206    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#207    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#208    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#209    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#210    Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#211    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#212    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#213    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#214    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#215    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
#216    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#217    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#218    Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#219    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#220    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#221    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#222    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#223    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
#224    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#225    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#226    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6871)
#227    Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#228    Element.updateChildren (package:flutter/src/widgets/framework.dart:4024)
#229    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6896)
#230    Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#231    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#232    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#233    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#234    StatefulElement.update (package:flutter/src/widgets/framework.dart:5657)
#235    Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#236    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#237    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#238    ProxyElement.update (package:flutter/src/widgets/framework.dart:5800)
#239    Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#240    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#241    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#242    ProxyElement.update (package:flutter/src/widgets/framework.dart:5800)
#243    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:105)
#244    Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#245    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#246    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#247    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#248    StatefulElement.update (package:flutter/src/widgets/framework.dart:5657)
#249    Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#250    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#251    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#252    ProxyElement.update (package:flutter/src/widgets/framework.dart:5800)
#253    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:105)
#254    Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#255    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#256    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#257    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#258    StatefulElement.update (package:flutter/src/widgets/framework.dart:5657)
#259    Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#260    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#261    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#262    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#263    StatefulElement.update (package:flutter/src/widgets/framework.dart:5657)
#264    Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#265    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6743)
#266    Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#267    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6743)
#268    Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#269    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#270    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#271    ProxyElement.update (package:flutter/src/widgets/framework.dart:5800)
#272    Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#273    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#274    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#275    ProxyElement.update (package:flutter/src/widgets/framework.dart:5800)
#276    Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#277    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#278    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#279    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#280    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2895)
#281    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:984)
#282    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:457)
#283    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1325)
#284    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1255)
#285    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1113)
#286    _invoke (dart:ui/hooks.dart:312)
#287    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:383)
#288    _drawFrame (dart:ui/hooks.dart:283)

**Comment by ardera** [comment]
You need to depend on the `flutterpi_gstreamer_video_player` package and call `FlutterpiVideoPlayer.registerWith()` in the main, before the `runApp` call: https://pub.dev/packages/flutterpi_gstreamer_video_player

I'll fix the readme instructions to mention that.

**Comment by beniskopf** [comment]
thanks for your help. I've included the `flutterpi_gstreamer_video_player` package and called `FlutterpiVideoPlayer.registerWith()`.  now i get this error message: 

```
> rp@raspberrypi:~ $ sudo flutter-pi --release -r 270 my_apps_flutter_assets/
error: XDG_RUNTIME_DIR is invalid or not set in the environment.
plugins/gstreamer_video_player/plugin.c: Couldn't create gstreamer video player.
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(nativeerror, Input/output error, 5, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:651)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:322)
<asynchronous suspension>
#2      FlutterpiVideoPlayer.create (package:flutterpi_gstreamer_video_player/src/platform.dart:78)
<asynchronous suspension>
#3      VideoPlayerController.initialize (package:video_player/video_player.dart:434)
<asynchronous suspension>
#4      _VideoPlayerScreenState.initState.<anonymous closure> (package:miata_screen/filepicker.dart:104)
<asynchronous suspension>
```

i tried to play the video using `gst-launch-1.0 playbin uri=file:///home/rp/media/mtv.mp4` and it works but the colors are distorted.

**Comment by ardera** [comment]
Are you on the latest revision of flutter-pi? This looks like a bug I fixed 3 weeks ago :)

**Comment by beniskopf** [comment]
sorry i'm retarded. `_controller.play();` was missing.
