### ISSUE TITLE
I updated the flutter version and reported the following error.(3.19.3)

### ISSUE THREAD

**Issue by meishiqi** [ardera/flutter-pi#399]
![image](https://github.com/ardera/flutter-pi/assets/69063519/72b3d9bb-d8b2-4b15-988f-fc81b11bc897)

**Comment by ardera** [comment]
Can you try running `flutter pub global activate flutterpi_tool` again? That'll update the tool. Though because of some other problem, the binaries for 3.19.3 are not yet available: https://github.com/ardera/flutterpi_tool/issues/13 (if you run into that problem, just wait a bit or use 3.19.2)

**Comment by meishiqi** [comment]
Thank You! I've switched to  3.19.2

**Comment by ardera** [comment]
👍  3.19.3 also works now if you want to upgrade.
