### ISSUE TITLE
screen ratio not respected.

### ISSUE THREAD

**Issue by shifubrams** [ardera/flutter-pi#407]
Hello, 
we are implementing a flutter solution on a 800x480 DSI screen. 
Meant to work on raspberry of course. 

The issue we encounter is that the ratio seems bigger thant expected. 

We tried the  older version of flutter-pi and flutterpi_tools and the ration was perfect. 

Is it a known issue on your side ? 
Do you have any solution for us ? 

Thanks in advance. 

You made a great job with this. Big thanks for that :)

**Comment by ardera** [comment]
Are you using the `-d` or `--dimensions` argument to set a custom screen size? If yes, can you try again with master?

Can you send me a link to the exact screen you have?
