### ISSUE TITLE
./include/plugins/gpiod.h:4:10: fatal error: gpiod.h: No such file or directory

### ISSUE THREAD

**Issue by danialhedaiat** [ardera/flutter-pi#41]
when i do make command in flutter-pi directory it raise it error for me

> ./include/plugins/gpiod.h:4:10: fatal error: gpiod.h: No such file or directory

> #include <gpiod.h>

can you guys help me

**Comment by danialhedaiat** [comment]
when i do make command in flutter-pi directory it raise it error for me 
./include/plugins/gpiod.h:4:10: fatal error: gpiod.h: No such file or directory
 #include <gpiod.h>

**Comment by limbouser** [comment]
Try this
`sudo apt-get install gpiod libgpiod-dev`

**Comment by danialhedaiat** [comment]
> Try this
> `sudo apt-get install gpiod libgpiod-dev`

well done, thank you, you are the best
