### ISSUE TITLE
RK3566 board get black screen with a cursor

### ISSUE THREAD

**Issue by sparrowu93** [ardera/flutter-pi#429]
I’m using an RK3566 board with a touch screen with lvds connector. When I run the `kmscube` command, everything works fine.
And then After running command 
`sudo flutter-pi -r 270 my_assets`
the console print debug info below and after that exit leave black screen with a white cursor.
<details>
<summary>debug log</summary>

    ==============Locale==============
    Flutter locale:
      default: zh
      locales: zh zh.UTF-8 zh_CN zh.UTF-8 zh.UTF-8 zh_CN zh.UTF-8
    ===================================
    modesetting.c: Could not set DRM client atomic capable. drmSetClientCap: Invalid argument
    flutter-pi.c: Could not create drmdev from device at "/dev/dri/card1". Continuing.
    modesetting.c: Unknown DRM connector property: CONNECTOR_ID
    modesetting.c: Unknown DRM connector property: brightness
    modesetting.c: Unknown DRM connector property: contrast
    modesetting.c: Unknown DRM connector property: saturation
    modesetting.c: Unknown DRM connector property: hue
    modesetting.c: Unknown DRM crtc property: SOC_ID
    modesetting.c: Unknown DRM crtc property: PORT_ID
    modesetting.c: Unknown DRM crtc property: ACLK
    modesetting.c: Unknown DRM crtc property: BACKGROUND
    modesetting.c: Unknown DRM crtc property: LINE_FLAG1
    modesetting.c: Unknown DRM crtc property: left margin
    modesetting.c: Unknown DRM crtc property: right margin
    modesetting.c: Unknown DRM crtc property: top margin
    modesetting.c: Unknown DRM crtc property: bottom margin
    modesetting.c: Unknown DRM crtc property: PLANE_MASK
    modesetting.c: Unknown DRM crtc property: CUBIC_LUT
    modesetting.c: Unknown DRM crtc property: CUBIC_LUT_SIZE
    modesetting.c: Unknown DRM crtc property: SOC_ID
    modesetting.c: Unknown DRM crtc property: PORT_ID
    modesetting.c: Unknown DRM crtc property: ACLK
    modesetting.c: Unknown DRM crtc property: BACKGROUND
    modesetting.c: Unknown DRM crtc property: LINE_FLAG1
    modesetting.c: Unknown DRM crtc property: left margin
    modesetting.c: Unknown DRM crtc property: right margin
    modesetting.c: Unknown DRM crtc property: top margin
    modesetting.c: Unknown DRM crtc property: bottom margin
    modesetting.c: Unknown DRM crtc property: PLANE_MASK
    gl_renderer.c: Could not get EGL display from GBM device. eglGetPlatformDisplay: EGL_SUCCESS
    gl_renderer.c: Attempting eglGetPlatformDisplayEXT...
    arm_release_ver of this libmali is 'g2p0-01eac0', rk_so_ver is '4'.
    ===================================
    EGL information:
      version: 1.4 Bifrost-"g2p0-01eac0"
      vendor: ARM
      client extensions: EGL_EXT_client_extensions EGL_EXT_platform_base EGL_KHR_client_get_all_proc_addresses EGL_KHR_platform_x11 EGL_EXT_platform_x11 EGL_KHR_platform_gbm
      display extensions: EGL_KHR_partial_update EGL_KHR_config_attribs EGL_KHR_image EGL_KHR_image_base EGL_KHR_fence_sync EGL_KHR_wait_sync EGL_KHR_gl_colorspace EGL_KHR_get_all_proc_addresses EGL_IMG_context_priority EGL_KHR_no_config_context EGL_EXT_image_dma_buf_import EGL_EXT_image_dma_buf_import_modifiers EGL_EXT_yuv_surface EGL_EXT_pixel_format_float EGL_ARM_pixmap_multisample_discard EGL_ARM_implicit_external_sync EGL_KHR_gl_texture_2D_image EGL_KHR_gl_renderbuffer_image EGL_KHR_create_context EGL_KHR_surfaceless_context EGL_KHR_gl_texture_cubemap_image EGL_EXT_image_gl_colorspace EGL_EXT_create_context_robustness
    ===================================
    ===================================
    OpenGL ES information:
      version: "OpenGL ES 3.2 v1.g2p0-01eac0.327c41db9c110a33ae6f67b4cc0581c7"
      shading language version: "OpenGL ES GLSL ES 3.20"
      vendor: "ARM"
      renderer: "Mali-G52"
      extensions: "GL_ARM_rgba8 GL_ARM_mali_shader_binary GL_OES_depth24 GL_OES_depth_texture GL_OES_depth_texture_cube_map GL_OES_packed_depth_stencil GL_OES_rgb8_rgba8 GL_EXT_read_format_bgra GL_OES_compressed_paletted_texture GL_OES_compressed_ETC1_RGB8_texture GL_OES_standard_derivatives GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_image_external_essl3 GL_OES_EGL_sync GL_OES_texture_npot GL_OES_vertex_half_float GL_OES_required_internalformat GL_OES_vertex_array_object GL_OES_mapbuffer GL_EXT_texture_format_BGRA8888 GL_EXT_texture_rg GL_EXT_texture_type_2_10_10_10_REV GL_OES_fbo_render_mipmap GL_OES_element_index_uint GL_EXT_shadow_samplers GL_OES_texture_compression_astc GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_hdr GL_KHR_texture_compression_astc_sliced_3d GL_EXT_texture_compression_astc_decode_mode GL_EXT_texture_compression_astc_decode_mode_rgb9e5 GL_KHR_debug GL_EXT_occlusion_query_boolean GL_EXT_disjoint_timer_query GL_EXT_blend_minmax GL_EXT_discard_framebuffer GL_OES_get_program_binary GL_OES_texture_3D GL_EXT_texture_storage GL_EXT_multisampled_render_to_texture GL_EXT_multisampled_render_to_texture2 GL_OES_surfaceless_context GL_OES_texture_stencil8 GL_EXT_shader_pixel_local_storage GL_ARM_shader_framebuffer_fetch GL_ARM_shader_framebuffer_fetch_depth_stencil GL_ARM_mali_program_binary GL_EXT_sRGB GL_EXT_sRGB_write_control GL_EXT_texture_sRGB_decode GL_EXT_texture_sRGB_R8 GL_EXT_texture_sRGB_RG8 GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_OES_texture_storage_multisample_2d_array GL_OES_shader_image_atomic GL_EXT_robustness GL_EXT_draw_buffers_indexed GL_OES_draw_buffers_indexed GL_EXT_texture_border_clamp GL_OES_texture_border_clamp GL_EXT_texture_cube_map_array GL_OES_texture_cube_map_array GL_OES_sample_variables GL_OES_sample_shading GL_OES_shader_multisample_interpolation GL_EXT_shader_io_blocks GL_OES_shader_io_blocks GL_EXT_tessellation_shader GL_OES_tessellation_shader GL_EXT_primitive_bounding_box GL_OES_primitive_bounding_box GL_EXT_geometry_shader GL_OES_geometry_shader GL_ANDROID_extension_pack_es31a GL_EXT_gpu_shader5 GL_OES_gpu_shader5 GL_EXT_texture_buffer GL_OES_texture_buffer GL_EXT_copy_image GL_OES_copy_image GL_EXT_shader_non_constant_global_initializers GL_EXT_color_buffer_half_float GL_EXT_color_buffer_float GL_EXT_YUV_target GL_OVR_multiview GL_OVR_multiview2 GL_OVR_multiview_multisampled_render_to_texture GL_KHR_robustness GL_KHR_robust_buffer_access_behavior GL_EXT_draw_elements_base_vertex GL_OES_draw_elements_base_vertex GL_EXT_buffer_storage GL_EXT_texture_filter_anisotropic GL_ARM_texture_unnormalized_coordinates "
    ===================================
    window.c: INFO: display has non-square pixels. Non-square-pixels are not supported by flutter.
    display mode:
      resolution: 1920 x 1080
      refresh rate: 60.000000Hz
      physical size: 155mm x 86mm
      flutter device pixel ratio: 3.259762
      pixel format: (any)
    pluginregistry.c: Initialized plugins: services, text input, raw keyboard plugin,
    window.c: Flutter requested render surface before supplying surface dimensions.
    gl_renderer.c: Choosing EGL config with pixel format ARGB 8:8:8:8...
    flutter: The Dart VM service is listening on http://127.0.0.1:41331/XXs_XIglATA=/
</details>
and when running  `dmesg | grep drm`
it's get output below 
<details>
<summary>dmesg | grep drm</summary>

        dmesg | grep drm
        [    0.235622] rockchip-drm display-subsystem: Linked as a consumer to fe040000.vop
        [    0.237059] rockchip-drm display-subsystem: Linked as a consumer to fe060000.dsi
        [    0.238279] rockchip-drm display-subsystem: defer getting devfreq
        [    0.238534] rockchip-vop2 fe040000.vop: [drm:vop2_bind] vp0 assign plane mask: 0x2a, primary plane phy id: 5
        [    0.238561] rockchip-vop2 fe040000.vop: [drm:vop2_bind] vp1 assign plane mask: 0x15, primary plane phy id: 4
        [    0.238581] rockchip-vop2 fe040000.vop: [drm:vop2_bind] vp2 assign plane mask: 0x0, primary plane phy id: -1
        [    0.238668] [drm] unsupported AFBC format[3432564e]
        [    0.238718] rockchip-vop2 fe040000.vop: [drm:vop2_bind] Cluster1-win0 as cursor plane for vp0
        [    0.238837] rockchip-vop2 fe040000.vop: [drm:vop2_bind] Cluster0-win0 as cursor plane for vp1
        [    0.238921] [drm] failed to init overlay plane Cluster0-win1
        [    0.238937] [drm] failed to init overlay plane Cluster1-win1
        [    0.239074] rockchip-drm display-subsystem: bound fe040000.vop (ops 0xffffff8008d60290)
        [    0.239119] dw-mipi-dsi fe060000.dsi: [drm:dw_mipi_dsi_bind] *ERROR* Failed to find panel or bridge: -517
        [    2.497047] rockchip-drm display-subsystem: defer getting devfreq
        [    2.497345] rockchip-vop2 fe040000.vop: [drm:vop2_bind] vp0 assign plane mask: 0x2a, primary plane phy id: 5
        [    2.497369] rockchip-vop2 fe040000.vop: [drm:vop2_bind] vp1 assign plane mask: 0x15, primary plane phy id: 4
        [    2.497386] rockchip-vop2 fe040000.vop: [drm:vop2_bind] vp2 assign plane mask: 0x0, primary plane phy id: -1
        [    2.497494] rockchip-vop2 fe040000.vop: [drm:vop2_bind] Cluster1-win0 as cursor plane for vp0
        [    2.497589] rockchip-vop2 fe040000.vop: [drm:vop2_bind] Cluster0-win0 as cursor plane for vp1
        [    2.497657] [drm] failed to init overlay plane Cluster0-win1
        [    2.497668] [drm] failed to init overlay plane Cluster1-win1
        [    2.497785] rockchip-drm display-subsystem: bound fe040000.vop (ops 0xffffff8008d60290)
        [    2.497837] rockchip-drm display-subsystem: bound fe060000.dsi (ops 0xffffff8008d64c90)
        [    2.497851] [drm] Supports vblank timestamp caching Rev 2 (21.10.2013).
        [    2.497857] [drm] No driver support for vblank timestamp query.
        [    2.521608] rockchip-drm display-subsystem: fb0:  frame buffer device
        [    2.522314] [drm] Initialized rockchip 2.0.0 20140818 for display-subsystem on minor 0
        [    2.541973] [drm] Initialized rknpu 0.7.2 20220428 for fde40000.npu on minor 1
        [    7.665408] Freeing drm_logo memory: 732K
</details>

It would be nice if anyone could give some hint or anything I can do further like generate some debug info that helps!!

**Comment by ardera** [comment]
Hey sorry, while digging through my notifications I realized I completely missed this.

Is it still not working as of now?

Can you try the steps here: https://github.com/ardera/flutter-pi/wiki/debugging-output-issues
