### ISSUE TITLE
[Question] Raspberry Pi Zero/Zero W support

### ISSUE THREAD

**Issue by manchoz** [ardera/flutter-pi#56]
Hi,
is it possible to get `flutter-pi` running on a Raspberry Pi Zero (Raspberry Pi 1)?

I get an `Illegal instruction` error both with the flutter engine you provide and with one that I built from scratch (targeting armv6-linux-gnueabihf).

Thanks!

**Comment by manchoz** [comment]
Nevermind, it seems that [armv6 it's not supported](https://github.com/flutter/flutter/issues/55439#event-3267901549). Going to grab a Raspberry Pi 4.

**Comment by ardera** [comment]
Yeah, unfortunately dart doesn't support armv6 anymore.
I'm gonna update the readme to clarify this.
