### ISSUE TITLE
What is the memory footprint?

### ISSUE THREAD

**Issue by nanfang2000** [ardera/flutter-pi#67]
app size and memory usage?

**Comment by DisDis** [comment]
I have application
![image](https://user-images.githubusercontent.com/87201/87344081-7dffd900-c556-11ea-8930-c537ae581dd7.png)
RaPi4 (4Gb Ram)
flutter_assets ~ 31Mb

**Comment by nanfang2000** [comment]
@DisDis Thank you for you info!

**Comment by nanfang2000** [comment]
338MB-63MB=275MB! That is a surprise number.
My test on Flutter Mac desktop app shows the release version is only 70MB.
the debug version is bigger which is 200+MB. So I guess your number is based on debug version? @DisDis 

I would like to porting flutter to a low end device which only has 128MB memory. so now I'm wondering whether it is feasible.

**Comment by ardera** [comment]
> So I guess your number is based on debug version?

Yeah flutter-pi only supports debug mode right now. Though I'm working on AOT support.

**Comment by DisDis** [comment]
After enabling AOT.
I have 200mb-74mb=126Mb
![image](https://user-images.githubusercontent.com/87201/88979159-cd216a00-d2c9-11ea-9f3b-e3d7da1d1885.png)

**Comment by ardera** [comment]
I have a small test app that is just a Scaffold with an AppBar and a Chewie Player playing back an MP4 fetched via web.

- flutter-pi process: virt 214M, res 52M, shr 35M.
- separate omxplayer process that actually plays back the video: res 39M, shr 21M
