### ISSUE TITLE
Error on Make

### ISSUE THREAD

**Issue by queirozrphl** [ardera/flutter-pi#80]
Hi guys, today I've seem a weird error at making the project. 
I'll put all commands that I used. 

1) Normal clone

> pi@raspberrypi:~/flutter-engine $ git clone https://github.com/ardera/flutter-pi.git
> Cloning into 'flutter-pi'...
> remote: Enumerating objects: 166, done.
> remote: Counting objects: 100% (166/166), done.
> remote: Compressing objects: 100% (123/123), done.
> remote: Total 869 (delta 92), reused 87 (delta 41), pack-reused 703
> Receiving objects: 100% (869/869), 55.30 MiB | 2.03 MiB/s, done.
> Resolving deltas: 100% (534/534), done.

2) Normal make
`pi@raspberrypi:~/flutter-engine/flutter-pi $ make
cc -c -I./include -I/usr/include/libdrm -DBUILD_TEXT_INPUT_PLUGIN -DBUILD_GPIOD_PLUGIN -DBUILD_SPIDEV_PLUGIN -DBUILD_TEST_PLUGIN -DBUILD_OMXPLAYER_VIDEO_PLAYER_PLUGIN -O0 -ggdb  src/flutter-pi.c -o out/obj/flutter-pi.o
In file included from src/flutter-pi.c:45:
./include/flutter-pi.h:59:58: error: unknown type name ‘FlutterEngineAOTDataSource’
  FlutterEngineResult (*FlutterEngineCreateAOTData)(const FlutterEngineAOTDataSource* source, FlutterEngineAOTData* data_out);
                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
./include/flutter-pi.h:59:94: error: unknown type name ‘FlutterEngineAOTData’; did you mean ‘FlutterEngineResult’?
  FlutterEngineResult (*FlutterEngineCreateAOTData)(const FlutterEngineAOTDataSource* source, FlutterEngineAOTData* data_out);
                                                                                              ^~~~~~~~~~~~~~~~~~~~
                                                                                              FlutterEngineResult
./include/flutter-pi.h:60:53: error: unknown type name ‘FlutterEngineAOTData’; did you mean ‘FlutterEngineResult’?
  FlutterEngineResult (*FlutterEngineCollectAOTData)(FlutterEngineAOTData data);
                                                     ^~~~~~~~~~~~~~~~~~~~
                                                     FlutterEngineResult
src/flutter-pi.c: In function ‘init_application’:
src/flutter-pi.c:1583:2: error: unknown type name ‘FlutterEngineAOTDataSource’; did you mean ‘FlutterEngineDartPort’?
  FlutterEngineAOTDataSource aot_source;
  ^~~~~~~~~~~~~~~~~~~~~~~~~~
  FlutterEngineDartPort
src/flutter-pi.c:1586:2: error: unknown type name ‘FlutterEngineAOTData’; did you mean ‘FlutterEngineResult’?
  FlutterEngineAOTData aot_data;
  ^~~~~~~~~~~~~~~~~~~~
  FlutterEngineResult
src/flutter-pi.c:1625:30: error: ‘struct libflutter_engine’ has no member named ‘FlutterEngineCreateAOTData’; did you mean ‘FlutterEngineUpdateLocales’?
  LOAD_LIBFLUTTER_ENGINE_PROC(FlutterEngineCreateAOTData);
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~
src/flutter-pi.c:1618:23: note: in definition of macro ‘LOAD_LIBFLUTTER_ENGINE_PROC’
    libflutter_engine->name = dlsym(libflutter_engine_handle, #name); \
                       ^~~~
src/flutter-pi.c:1625:30: error: ‘struct libflutter_engine’ has no member named ‘FlutterEngineCreateAOTData’; did you mean ‘FlutterEngineUpdateLocales’?
  LOAD_LIBFLUTTER_ENGINE_PROC(FlutterEngineCreateAOTData);
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~
src/flutter-pi.c:1619:28: note: in definition of macro ‘LOAD_LIBFLUTTER_ENGINE_PROC’
    if (!libflutter_engine->name) {\
                            ^~~~
src/flutter-pi.c:1626:30: error: ‘struct libflutter_engine’ has no member named ‘FlutterEngineCollectAOTData’; did you mean ‘FlutterEngineRunTask’?
  LOAD_LIBFLUTTER_ENGINE_PROC(FlutterEngineCollectAOTData);
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~
src/flutter-pi.c:1618:23: note: in definition of macro ‘LOAD_LIBFLUTTER_ENGINE_PROC’
    libflutter_engine->name = dlsym(libflutter_engine_handle, #name); \
                       ^~~~
src/flutter-pi.c:1626:30: error: ‘struct libflutter_engine’ has no member named ‘FlutterEngineCollectAOTData’; did you mean ‘FlutterEngineRunTask’?
  LOAD_LIBFLUTTER_ENGINE_PROC(FlutterEngineCollectAOTData);
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~
src/flutter-pi.c:1619:28: note: in definition of macro ‘LOAD_LIBFLUTTER_ENGINE_PROC’
    if (!libflutter_engine->name) {\
                            ^~~~
src/flutter-pi.c:1746:17: error: ‘FlutterEngineAOTDataSource’ undeclared (first use in this function); did you mean ‘FlutterEngineDartPort’?
   aot_source = (FlutterEngineAOTDataSource) {
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~
                 FlutterEngineDartPort
src/flutter-pi.c:1746:17: note: each undeclared identifier is reported only once for each function it appears in
src/flutter-pi.c:1746:44: error: expected ‘;’ before ‘{’ token
   aot_source = (FlutterEngineAOTDataSource) {
                                            ^~
                                            ;
src/flutter-pi.c:1751:38: error: ‘struct libflutter_engine’ has no member named ‘FlutterEngineCreateAOTData’; did you mean ‘FlutterEngineUpdateLocales’?
   engine_result = libflutter_engine->FlutterEngineCreateAOTData(&aot_source, &aot_data);
                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~
                                      FlutterEngineUpdateLocales
src/flutter-pi.c:1757:15: error: ‘FlutterProjectArgs’ {aka ‘struct <anonymous>’} has no member named ‘aot_data’
   project_args.aot_data = aot_data;
               ^
make: *** [Makefile:42: out/obj/flutter-pi.o] Error 1`

Someone has the same mistake before?

**Comment by ardera** [comment]
You need to update your engine binaries to 1.20.
More precisely, this error is caused by an outdated `flutter_embedder.h`, but I assume your flutter engine library (/-ies) and `icudtl.dat` are outdated as well. See the readme in the `engine-binaries` branch on how to update them.
