### ISSUE TITLE
GPIO access

### ISSUE THREAD

**Issue by jogiji** [ardera/flutter-pi#9]
Can we have GPIO access of some sort with this implementation ?? Just asking

**Comment by ardera** [comment]
Yeah, that's a good idea.

**Comment by akilinomendez** [comment]
Alternatively you can create a backend with flask or django and call with dio in flutter to execute gpio commands using python.

Is tested and working

**Comment by ardera** [comment]
> Alternatively you can create a backend with flask or django and call with dio in flutter to execute gpio commands using python.
> 
> Is tested and working

That's kinda overkill but yeah, sounds like that should be working.

I found a package that does exactly what you want: https://pub.dev/packages/rpi_gpio

Only works for Raspberry Pi though, while flutter-pi (despite its name) works on much more embedded devices.

**Comment by mortenboye** [comment]
Here’s another vote for GPIO access or maybe just a wiki page showing how to write and use plugins with flutter-pi (unless dart:ffi gets working soon)

**Comment by ardera** [comment]
> Here’s another vote for GPIO access (unless dart:ffi gets working soon)

Yeah actually I started work on GPIO access using `dart:ffi` and `libgpiod` a while ago, because it's probably faster than platform channels. Had basic functionality going & was ready to test, then I found out `dart:ffi` isn't yet supported on ARM hardfp platforms.

**Comment by mortenboye** [comment]
> > Here’s another vote for GPIO access (unless dart:ffi gets working soon)
> 
> Yeah actually I started work on GPIO access using `dart:ffi` and `libgpiod` a while ago, because it's probably faster than platform channels. Had basic functionality going & was ready to test, then I found out `dart:ffi` isn't yet supported on ARM hardfp platforms.

So, how did you solve this challenge? Write a flutter plugin for GPIO?

**Comment by ardera** [comment]
> So, how did you solve this challenge? Write a flutter plugin for GPIO?

I didn't (yet).

**Comment by ardera** [comment]
GPIO (more precisely, `libgpiod`) support is now integrated into `flutter-pi`.
The [dart interface](https://github.com/ardera/flutter_gpiod) still needs some work. Once it's done, I'll publish it on [pub.dev](https://pub.dev).

**Comment by ardera** [comment]
Just [published it.](https://pub.dev/packages/flutter_gpiod)

**Comment by mortenboye** [comment]
dart:ffi seems to be working with hardfp by now, according to https://github.com/dart-lang/sdk/commit/a71d60c1cf9ff350d4f216b62aa44835182d98f5

@ardera Any chance you could share your FFI based plugin for reference?

**Comment by ardera** [comment]
> dart:ffi seems to be working with hardfp by now, according to [dart-lang/sdk@a71d60c](https://github.com/dart-lang/sdk/commit/a71d60c1cf9ff350d4f216b62aa44835182d98f5)

Nice! Keep in mind though that this feature is only available to flutter once the next stable version of the dart SDK (2.8) is released. I'll consider migrating the `flutter_gpiod` package to `dart:ffi` once that happens. That would mean a lot of the ugly async stuff, mutexes, etc in `flutter_gpiod` can go away.

> @ardera Any chance you could share your FFI based plugin for reference?

Sure. The code is _reaally_ ugly, very far from finished and doesn't look like the code of the `flutter_gpiod` package at all, though. I was just kinda experimenting.

[flutter_gpiod_ffi.zip](https://github.com/ardera/flutter-pi/files/4409463/flutter_gpiod_ffi.zip)

**Comment by hhk7734** [comment]
Test environment
* OS: Linux kernel 5.4, ubuntu 20.04 minimal
* HW: s905x3 board

Thank you :)
flutter_gpiod works well.
